// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/dzamyatin/atomWebsite/internal/grpc/grpc"
	"github.com/dzamyatin/atomWebsite/internal/repository"
	"github.com/dzamyatin/atomWebsite/internal/service/process"
	"github.com/dzamyatin/atomWebsite/internal/usecase"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from di.go:

func InitializeGRPCProcessManager() (*process.ProcessManager, error) {
	logger := newLogger()
	db, err := newDb()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	registrationUseCase := usecase.NewRegistrationUseCase(userRepository)
	authServer := grpc.NewAuthServer(registrationUseCase)
	server := newGrpcServer(authServer)
	grpcServer := newServer(server)
	signalListener := process.NewSignalListener(logger)
	processManager := newGRPCProcessManager(logger, grpcServer, signalListener, db)
	return processManager, nil
}
