// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/dzamyatin/atomWebsite/internal/entity"
	"github.com/dzamyatin/atomWebsite/internal/grpc/grpc"
	"github.com/dzamyatin/atomWebsite/internal/repository"
	"github.com/dzamyatin/atomWebsite/internal/service/auth"
	"github.com/dzamyatin/atomWebsite/internal/service/bus"
	"github.com/dzamyatin/atomWebsite/internal/service/cmd/executors"
	"github.com/dzamyatin/atomWebsite/internal/service/db"
	"github.com/dzamyatin/atomWebsite/internal/service/handler"
	"github.com/dzamyatin/atomWebsite/internal/service/messenger/statemachine"
	"github.com/dzamyatin/atomWebsite/internal/service/messenger/statemachine/state"
	"github.com/dzamyatin/atomWebsite/internal/service/metric"
	"github.com/dzamyatin/atomWebsite/internal/service/process"
	"github.com/dzamyatin/atomWebsite/internal/service/time"
	"github.com/dzamyatin/atomWebsite/internal/service/user"
	"github.com/dzamyatin/atomWebsite/internal/usecase"
	"github.com/dzamyatin/atomWebsite/internal/usecase/messenger"
	"github.com/dzamyatin/atomWebsite/internal/usecase/migration"
	"github.com/dzamyatin/atomWebsite/internal/validator"
	"github.com/google/wire"
	"go.uber.org/zap"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
	_ "github.com/lib/pq"
	_ "github.com/prometheus/client_golang/prometheus/promhttp"
)

// Injectors from command.go:

func InitializeMigrationUpCommand(ctx context.Context) (*executors.MigrationUpCommand, error) {
	logger := newLogger()
	db, err := newDb(ctx)
	if err != nil {
		return nil, err
	}
	up := usecasemigration.NewUp(logger, db)
	migrationUpCommand := executors.NewMigrationUpCommand(logger, up)
	return migrationUpCommand, nil
}

func InitializeMigrationCreateCommand(ctx context.Context) *executors.MigrationCreateCommand {
	logger := newLogger()
	migrationCreateCommand := executors.NewMigrationCreateCommand(logger)
	return migrationCreateCommand
}

func InitializeMigrationDownCommand(ctx context.Context) (*executors.MigrationDownCommand, error) {
	logger := newLogger()
	db, err := newDb(ctx)
	if err != nil {
		return nil, err
	}
	down := usecasemigration.NewDown(logger, db)
	migrationDownCommand := executors.NewMigrationDownCommand(logger, down)
	return migrationDownCommand, nil
}

func InitializeBusProcessCommand(ctx context.Context) (*executors.BusProcessCommand, error) {
	logger := newLogger()
	sqlDB, err := newDb(ctx)
	if err != nil {
		return nil, err
	}
	sqlxDB, err := newDbx(sqlDB)
	if err != nil {
		return nil, err
	}
	database := db.NewDatabase(sqlxDB)
	postgresBus := newPostgresBus(database, logger)
	memoryBus := bus.NewMemoryBus()
	userRepository := repository.NewUserRepository(database)
	passwordEncoder := userservice.NewPasswordEncoder()
	iMailer := newMailer(logger)
	time := servicetime.NewTime()
	randomizerRepository := repository.NewRandomizerRepository(logger, database, time)
	sendEmailConfirmationUseCase := usecase.NewSendEmailConfirmationUseCase(logger, iMailer, randomizerRepository)
	registration := usecase.NewRegistration(userRepository, passwordEncoder, logger, iMailer, randomizerRepository, sendEmailConfirmationUseCase)
	registerHandler := handler.NewRegisterHandler(registration)
	handlerRegistry := newHandlerRegistry(registerHandler)
	mainBus := newBus(postgresBus, memoryBus, handlerRegistry, logger)
	busProcessCommand := executors.NewBusProcessCommand(logger, postgresBus, mainBus)
	return busProcessCommand, nil
}

func InitializeTelegramBotProcessCommand(ctx context.Context) (*executors.TelegramBotProcessCommand, error) {
	logger := newLogger()
	telegramDriver := newTelegramBotServer(logger)
	messengerServerRegistry := newMessengerServerRegistry(telegramDriver)
	sqlDB, err := newDb(ctx)
	if err != nil {
		return nil, err
	}
	sqlxDB, err := newDbx(sqlDB)
	if err != nil {
		return nil, err
	}
	database := db.NewDatabase(sqlxDB)
	chatRepository := repository.NewChatRepository(logger, database)
	initialState := servicemessengerstatemachinestate.NewInitialState(logger)
	waitForPhone := servicemessengerstatemachinestate.NewWaitForPhone(logger)
	iStateRegistry := newStateRegistry(logger, initialState, waitForPhone)
	stateMachineFactory := servicemessengerstatemachine.NewStateMachineFactory(logger, chatRepository, iStateRegistry)
	receiveMessageUseCase := usecasemessenger.NewReceiveMessageUseCase(logger, stateMachineFactory)
	telegramBotProcessCommand := executors.NewTelegramBotProcessCommand(logger, messengerServerRegistry, receiveMessageUseCase)
	return telegramBotProcessCommand, nil
}

// Injectors from di.go:

func InitializeGRPCProcessManager(ctx context.Context) (*process.ProcessManager, error) {
	logger := newLogger()
	sqlDB, err := newDb(ctx)
	if err != nil {
		return nil, err
	}
	sqlxDB, err := newDbx(sqlDB)
	if err != nil {
		return nil, err
	}
	database := db.NewDatabase(sqlxDB)
	userRepository := repository.NewUserRepository(database)
	passwordEncoder := userservice.NewPasswordEncoder()
	iMailer := newMailer(logger)
	time := servicetime.NewTime()
	randomizerRepository := repository.NewRandomizerRepository(logger, database, time)
	sendEmailConfirmationUseCase := usecase.NewSendEmailConfirmationUseCase(logger, iMailer, randomizerRepository)
	registration := usecase.NewRegistration(userRepository, passwordEncoder, logger, iMailer, randomizerRepository, sendEmailConfirmationUseCase)
	sequentialProvider := newSequentialProvider(userRepository, logger, passwordEncoder)
	jwt := newJWT(logger)
	login := usecase.NewLogin(logger, sequentialProvider, jwt)
	confirmEmailUseCase := usecase.NewConfirmEmailUseCase(userRepository, logger, randomizerRepository)
	postgresBus := newPostgresBus(database, logger)
	memoryBus := bus.NewMemoryBus()
	registerHandler := handler.NewRegisterHandler(registration)
	handlerRegistry := newHandlerRegistry(registerHandler)
	mainBus := newBus(postgresBus, memoryBus, handlerRegistry, logger)
	iSenderService := newMessenger(logger)
	rememberPasswordUseCase := usecase.NewRememberPasswordUseCase(userRepository, passwordEncoder, logger, iMailer, randomizerRepository, iSenderService)
	validatorValidator := validator.NewValidator()
	changePasswordUseCase := usecase.NewChangePasswordUseCase(logger, userRepository, randomizerRepository, passwordEncoder, passwordEncoder)
	authServer := grpc.NewAuthServer(registration, login, confirmEmailUseCase, mainBus, sendEmailConfirmationUseCase, rememberPasswordUseCase, validatorValidator, changePasswordUseCase)
	registry := metric.NewRegistry(logger)
	metricMetric := metric.NewMetric(logger, registry)
	server := newGrpcServer(authServer, metricMetric)
	grpcServer := newServer(server)
	signalListener := process.NewSignalListener(logger)
	httpServer := newHTTPServer(authServer)
	processManager := newGRPCProcessManager(logger, grpcServer, signalListener, sqlDB, registry, httpServer)
	return processManager, nil
}

func InitializeLogger(ctx context.Context) *zap.Logger {
	logger := newLogger()
	return logger
}

// di.go:

var set = wire.NewSet(
	newGRPCProcessManager,
	newLogger,
	newServer,
	newGrpcServer, grpc.NewAuthServer, process.NewSignalListener, usecase.NewRegistration, repository.NewUserRepository, wire.Bind(new(repository.IUserRepository), new(*repository.UserRepository)), newDb,
	newDbx, db.NewDatabase, wire.Bind(new(db.IDatabase), new(*db.Database)), wire.Bind(new(entity.PasswordEncoder), new(*userservice.PasswordEncoder)), wire.Bind(new(entity.PasswordComparator), new(*userservice.PasswordEncoder)), userservice.NewPasswordEncoder, usecasemigration.NewUp, usecasemigration.NewDown, metric.NewMetric, metric.NewRegistry, usecase.NewLogin, wire.Bind(new(serviceauth.IProvider), new(*serviceauth.SequentialProvider)), newSequentialProvider, wire.Bind(new(serviceauth.IJWT), new(*serviceauth.JWT)), newJWT, wire.Bind(new(bus.IBus), new(*bus.MainBus)), newBus,
	newHandlerRegistry, bus.NewMemoryBus, handler.NewRegisterHandler, executors.NewMigrationCreateCommand, executors.NewMigrationDownCommand, executors.NewMigrationUpCommand, newPostgresBus, executors.NewBusProcessCommand, newHTTPServer,
	newMailer, servicetime.NewTime, wire.Bind(new(servicetime.ITime), new(*servicetime.Time)), repository.NewRandomizerRepository, wire.Bind(new(repository.IRandomizerRepository), new(*repository.RandomizerRepository)), usecase.NewConfirmEmailUseCase, usecase.NewSendEmailConfirmationUseCase, newMessenger, usecase.NewRememberPasswordUseCase, validator.NewValidator, usecase.NewChangePasswordUseCase, newTelegramBotServer, executors.NewTelegramBotProcessCommand, wire.Bind(new(repository.IChatRepository), new(*repository.ChatRepository)), repository.NewChatRepository, servicemessengerstatemachinestate.NewInitialState, servicemessengerstatemachinestate.NewWaitForPhone, newStateRegistry, usecasemessenger.NewReceiveMessageUseCase, servicemessengerstatemachine.NewStateMachineFactory, newMessengerServerRegistry,
)
