###
GRPC localhost:8502/auth.Auth/Login

{
  "email": "test@test.ru",
  "password": "pwd",
  "phone": "+79991112233"
}

###
GRPC localhost:8502/auth.Auth/Register

{
  "email": "test@test.ru",
  "password": "pwd",
  "phone": "+79991112233"
}

###
GET http://localhost:9090/metrics

###
POST localhost:8503/register

{
  "email": "test@test.ru",
  "password": "pwd",
  "phone": "+79991112233"
}

###
OPTIONS localhost:8503/register

###
POST localhost:8503/confirm-email

{
  "email": "test@test.ru",
  "code": "123"
}